// This file is partially autogenerated by misc/python-tools/extract-starter-decks.py
//
// Only edit outside the AUTOGENERATED block below, or your changes will be overwritten.
define(['dojo', 'dojo/_base/declare'], (dojo, declare) => {
  
/* AUTOGENERATED extract-starter-decks BEGIN */
  const STARTER_DECK_META = {
  "AX": [
    { deckId: "ax_85_della", hero: _("Della & Bolt"), author: "Eldritch Madcap", description: _("starter_description_della"), },
    { deckId: "ax_65_isaree", hero: _("Isaree & Pebble"), author: "Vagamebond", description: _("starter_description_isaree"), },
    { deckId: "ax_1_sierra", hero: _("Sierra & Oddball"), author: "VaderMIB", description: _("starter_description_sierra"), },
    { deckId: "ax_3_subhash", hero: _("Subhash & Marmo"), author: "Netjery", description: _("starter_description_subhash"), },
    { deckId: "ax_2_treyst", hero: _("Treyst & Rossum"), author: "Rinku", description: _("starter_description_treyst"), },
  ],
  "BR": [
    { deckId: "br_2_atsadi", hero: _("Atsadi & Surge"), author: "VaderMIB", description: _("starter_description_atsadi"), },
    { deckId: "br_3_basira", hero: _("Basira & Kaizaimon"), author: "Spartacus", description: _("starter_description_basira"), },
    { deckId: "br_1_kojo", hero: _("Kojo & Booda"), author: "Cohlrabi", description: _("starter_description_kojo"), },
    { deckId: "br_65_sol", hero: _("Sol & Halua"), author: "Lyrael", description: _("starter_description_sol"), },
  ],
  "LY": [
    { deckId: "ly_2_auraq", hero: _("Auraq & Kibble"), author: "The_Vary", description: _("starter_description_auraq"), },
    { deckId: "ly_3_fen", hero: _("Fen & Crowbar"), author: "YllKa", description: _("starter_description_fen"), },
    { deckId: "ly_65_nadir", hero: _("Nadir & Bubbles"), author: "NyanKoro", description: _("starter_description_nadir"), },
    { deckId: "ly_1_nevenka", hero: _("Nevenka & Blotch"), author: "Knightsong", description: _("starter_description_nevenka"), },
  ],
  "MU": [
    { deckId: "mu_2_arjun", hero: _("Arjun & Spike"), author: "Zadibouc", description: _("starter_description_arjun"), },
    { deckId: "mu_65_kauri", hero: _("Kauri & Puff"), author: "Cernnunos", description: _("starter_description_kauri"), },
    { deckId: "mu_3_rin", hero: _("Rin & Orchid"), author: "Oriazzz", description: _("starter_description_rin"), },
    { deckId: "mu_1_teija", hero: _("Teija & Nauraa"), author: "Floboum", description: _("starter_description_teija"), },
    { deckId: "mu_85_turuun", hero: _("Turuun & Benih"), author: "Psyno", description: _("starter_description_turuun"), },
  ],
  "OD": [
    { deckId: "or_3_gulrang", hero: _("Gulrang & Tocsin"), author: "Rinku", description: _("starter_description_gulrang"), },
    { deckId: "or_85_matz", hero: _("Matz & Hive"), author: "Lykel", description: _("starter_description_matz"), },
    { deckId: "or_1_sigismar", hero: _("Sigismar & Wingspan"), author: "Rinku", description: _("starter_description_sigismar"), },
    { deckId: "or_2_waru", hero: _("Waru & Mack"), author: "Cernnunos", description: _("starter_description_waru"), },
    { deckId: "or_65_zhen", hero: _("Zhen & Zephyr"), author: "Mananka", description: _("starter_description_zhen"), },
  ],
  "YZ": [
    { deckId: "yz_3_afanas", hero: _("Afanas & Senka"), author: "Viko", description: _("starter_description_afanas"), },
    { deckId: "yz_1_akesha", hero: _("Akesha & Taru"), author: "CoraSan", description: _("starter_description_akesha"), },
    { deckId: "yz_2_lindiwe", hero: _("Lindiwe & Maw"), author: "Arthour", description: _("starter_description_lindiwe"), },
    { deckId: "yz_65_moyo", hero: _("Moyo & Silk"), author: "Elfiris", description: _("starter_description_moyo"), },
  ],
  };
/* AUTOGENERATED extract-starter-decks END */

  return declare('altered.starterDecks', null, {
    getStarterDecks() {
      return STARTER_DECK_META;
    },
  });
});
