// This file is partially autogenerated by misc/python-tools/extract-starter-decks.py
//
// Only edit outside the AUTOGENERATED block below, or your changes will be overwritten.
define(['dojo', 'dojo/_base/declare'], (dojo, declare) => {
  
/* AUTOGENERATED extract-starter-decks BEGIN */
  const STARTER_DECK_META = {
  "AX": [
    { deckId: "ax_85_della", hero: _("Della & Bolt"), author: "Eldritch Madcap", description: _("Use all your resources to the last drop, then recycle them once again!"), },
    { deckId: "ax_65_isaree", hero: _("Isaree & Pebble"), author: "Vagamebond", description: _("Create some beautiful things by breaking your old stuff!"), },
    { deckId: "ax_1_sierra", hero: _("Sierra & Oddball"), author: "VaderMIB", description: _("Use your team of robots to assemble the best robot factory!"), },
    { deckId: "ax_3_subhash", hero: _("Subhash & Marmo"), author: "Netjery", description: _("Even when you lack robots, you always have a Scarabot up your sleeve!"), },
    { deckId: "ax_2_treyst", hero: _("Treyst & Rossum"), author: "Rinku", description: _("Use your Reserve quickly and enable Treyst to find the cards you need!"), },
  ],
  "BR": [
    { deckId: "br_2_atsadi", hero: _("Atsadi & Surge"), author: "VaderMIB", description: _("Take time to build a strong Mana base then overwhelm your opponent with huge Characters!"), },
    { deckId: "br_3_basira", hero: _("Basira & Kaizaimon"), author: "Spartacus", description: _("Let boosts rain on your Characters and race to victory!"), },
    { deckId: "br_1_kojo", hero: _("Kojo & Booda"), author: "Cohlrabi", description: _("With Booda by your side, take control of the board with many powerful Characters or… eat them all!"), },
    { deckId: "br_65_sol", hero: _("Sol & Halua"), author: "Lyrael", description: _("No time to lose; rush to victory by passing first and leaving your opponent behind!"), },
  ],
  "LY": [
    { deckId: "ly_2_auraq", hero: _("Auraq & Kibble"), author: "The_Vary", description: _("Play many small Characters in order to summon your big ones for free!"), },
    { deckId: "ly_3_fen", hero: _("Fen & Crowbar"), author: "YllKa", description: _("Perform on stage and move all the cards from place to place until your opponent loses track!"), },
    { deckId: "ly_65_nadir", hero: _("Nadir & Bubbles"), author: "NyanKoro", description: _("Paint new Terrains to clear your way and lock your opponent in obstacles!"), },
    { deckId: "ly_1_nevenka", hero: _("Nevenka & Blotch"), author: "Knightsong", description: _("Ask for fate to give you some help but don't abuse it or you'll regret it!"), },
  ],
  "MU": [
    { deckId: "mu_2_arjun", hero: _("Arjun & Spike"), author: "Zadibouc", description: _("Make your Characters feel eternal by anchoring them over and over again!"), },
    { deckId: "mu_65_kauri", hero: _("Kauri & Puff"), author: "Cernnunos", description: _("Transform the board into a menagerie full of cute animals!"), },
    { deckId: "mu_3_rin", hero: _("Rin & Orchid"), author: "Oriazzz", description: _("Run through the forest and keep your Characters with you throughout the race!"), },
    { deckId: "mu_1_teija", hero: _("Teija & Nauraa"), author: "Floboum", description: _("In the hands of Teija, all your Characters are stronger than they seem, so keep them around!"), },
    { deckId: "mu_85_turuun", hero: _("Turuun & Benih"), author: "Psyno", description: _("Give gifts to your opponent and profit from them!"), },
  ],
  "OD": [
    { deckId: "or_3_gulrang", hero: _("Gulrang & Tocsin"), author: "Rinku", description: _("Watch your opponent pull ahead, then when you ring the bell, unleash all your power to catch up!"), },
    { deckId: "or_85_matz", hero: _("Matz & Hive"), author: "Lykel", description: _("Take your time to turn the board into a metropolis full of Landmarks!"), },
    { deckId: "or_1_sigismar", hero: _("Sigismar & Wingspan"), author: "Rinku", description: _("Always be present in both Expeditions in order to increase pressure!"), },
    { deckId: "or_2_waru", hero: _("Waru & Mack"), author: "Cernnunos", description: _("Let your Bureaucrats have a little nap while your opponent helps them grow!"), },
    { deckId: "or_65_zhen", hero: _("Zhen & Zephyr"), author: "Mananka", description: _("Ascend your Expeditions and fly over your opponent!"), },
  ],
  "YZ": [
    { deckId: "yz_3_afanas", hero: _("Afanas & Senka"), author: "Viko", description: _("Never stop playing spells and grow your tiny friends into big buddies!"), },
    { deckId: "yz_1_akesha", hero: _("Akesha & Taru"), author: "CoraSan", description: _("Let your opponent do the first move and use the right tool to adapt!"), },
    { deckId: "yz_2_lindiwe", hero: _("Lindiwe & Maw"), author: "Arthour", description: _("Summon your weird little companion and feed it Characters to make it grow!"), },
    { deckId: "yz_65_moyo", hero: _("Moyo & Silk"), author: "Elfiris", description: _("Cast big spells and overwhelm your opponent within a swarm of moths!"), },
  ],
  };
/* AUTOGENERATED extract-starter-decks END */

  return declare('altered.starterDecks', null, {
    getStarterDecks() {
      return STARTER_DECK_META;
    },
  });
});
