<?php

const PRECOS = [
  FACTION_AX => [
    'AX_Common_AmeliaEarhart' => 3,
    'AX_Common_ArmoredJammer' => 3,
    'AX_Common_AxiomReprocessor' => 2,
    'AX_Common_AxiomSalvager' => 3,
    'AX_Common_BrassbugHive' => 3,
    'AX_Common_Brassbug' => 4,
    'AX_Common_Ganesha' => 3,
    'AX_Common_JianAssemblyOverseer' => 2,
    'AX_Common_KelonElemental' => 3,
    'AX_Common_KelonSurge' => 3,
    'AX_Common_SierraOddball' => 1,
    'AX_Common_TinkerBell' => 2,
    'AX_Rare_AxiomReprocessor' => 1,
    'AX_Rare_JianAssemblyOverseer' => 1,
    'AX_Rare_TinkerBell' => 1,
  ],

  FACTION_BR => [
    'BR_Common_Atlas' => 3,
    'BR_Common_Booda' => 1,
    'BR_Common_BravosPathfinder' => 3,
    'BR_Common_BravosTracer' => 2,
    'BR_Common_HavenTrainee' => 3,
    'BR_Common_HavenBouncer' => 3,
    'BR_Common_HavenVeteran' => 3,
    'BR_Common_HuaMulan' => 2,
    'BR_Common_Intimidation' => 3,
    'BR_Common_KojoBooda' => 1,
    'BR_Common_PhysicalTraining' => 3,
    'BR_Common_Ratatoskr' => 2,
    'BR_Rare_BravosTracer' => 1,
    'BR_Rare_HuaMulan' => 1,
    'BR_Rare_Ratatoskr' => 1,
  ],

  FACTION_LY => [
    'LY_Common_AllIn' => 3,
    'LY_Common_Asmodeus' => 2,
    'LY_Common_ClothCocoon' => 3,
    'LY_Common_Esmeralda' => 2,
    'LY_Common_Hathor' => 1,
    'LY_Common_LyraChronicler' => 3,
    'LY_Common_LyraClothDancer' => 3,
    'LY_Common_LyraSkald' => 3,
    'LY_Common_NevenkaBlotch' => 1,
    'LY_Common_OuroborosDealer' => 3,
    'LY_Common_OuroborosTrickster' => 2,
    'LY_Rare_ALTAsmodeus' => 1,
    'LY_Rare_ALTEsmeralda' => 1,
    'LY_Rare_ALTOuroborosTrickster' => 1,
  ],

  FACTION_MU => [
    'MU_Common_Cernunnos' => 3,
    'MU_Common_ConiferalConeman' => 2,
    'MU_Common_DaughterofYggdrasil' => 3,
    'MU_Common_Inari' => 3,
    'MU_Common_Kitsune' => 3,
    'MU_Common_MeditationTraining' => 3,
    'MU_Common_MunaDruid' => 3,
    'MU_Common_Nurture' => 2,
    'MU_Common_SneezerShroom' => 2,
    'MU_Common_SpindleHarvesters' => 3,
    'MU_Common_TeijaNauraa' => 1,
    'MU_Rare_ALTConiferalConeman' => 1,
    'MU_Rare_ALTNurture' => 1,
    'MU_Rare_SneezerShroom' => 1,
  ],

  FACTION_OD => [
    'OD_Common_Charge' => 3,
    'OD_Common_JeannedArc' => 2,
    'OD_Common_KakobaLegionCommander' => 2,
    'OD_Common_OrdisCadets' => 3,
    'OD_Common_OrdisCarrier' => 3,
    'OD_Common_OrdisRecruit' => 3,
    'OD_Common_OrdisSpy' => 3,
    'OD_Common_OrdisTrooper' => 3,
    'OD_Common_Ozma' => 2,
    'OD_Common_SigismarWingspan' => 1,
    'OD_Common_StickyNotesSeals' => 3,
    'OD_Common_TheFrogPrince' => 3,
    'OD_Rare_ALTJeannedArc' => 1,
    'OD_Rare_ALTKakobaLegionCommander' => 1,
    'OD_Rare_ALTOzma' => 1,
  ],

  FACTION_YZ => [
    'YZ_Common_AkeshaTaru' => 1,
    'YZ_Common_Alice' => 3,
    'YZ_Common_DorothyGale' => 2,
    'YZ_Common_KadigiranAlchemist' => 2,
    'YZ_Common_KrakensWrath' => 3,
    'YZ_Common_LadyoftheLake' => 3,
    'YZ_Common_OffYouGo' => 3,
    'YZ_Common_Sakarabru' => 3,
    'YZ_Common_SpyCraft' => 2,
    'YZ_Common_StubbornDisciple' => 3,
    'YZ_Common_YzmirStargazer' => 3,
    'YZ_Rare_ALTKadigiranAlchemist' => 1,
    'YZ_Rare_ALTSpyCraft' => 1,
    'YZ_Rare_DorothyGale' => 1,
  ],
];
