<?php

namespace ALT;

const OPTION_CONFIRM = 103;
const OPTION_CONFIRM_DISABLED = 0;
const OPTION_CONFIRM_ENABLED = 2;
const OPTION_CONFIRM_TIMER = 3;

const OPTION_CONFIRM_UNDOABLE = 104;
const OPTION_PLAYER_UNDO = 152;
const OPTION_PLAYER_UNDO_ENABLED = 1;
const OPTION_PLAYER_UNDO_DISABLED = 2;
